//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::guild::Entity as Guild;
pub use super::channel_prompt::Entity as ChannelPrompt;
pub use super::global_prompt::Entity as GlobalPrompt;
