//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub mod prelude;

pub mod guild;
pub mod channel_prompt;
pub mod global_prompt;
pub mod bot_disposition;
pub mod user_insight;
pub mod user_directory;
pub mod channel_roleplay;
pub mod guild_roleplay;
